[package]
name = "ppjson"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "Apache-2.0/MIT"

[dependencies]
json-color = { git = "https://github.com/luser/json-color", branch = "preserve-order" }
pager = "0.14.0"
